// packages/demo/app/components/Ui/SearchInput.vue
<script setup>
defineOptions({
  inheritAttrs: false
});

const model = defineModel();
</script>

<template>
  <input
    v-bind="$attrs"
    v-model="model"
    type="text"
    placeholder="Search"
    class="font-serif w-full border-gray-300 border-2 px-3 py-2 rounded-full focus:outline-none focus:border-blue-500"
    autofocus
  />
</template>

// packages/demo-svelte/src/components/SearchInput.svelte
<script lang="ts">
  let { value = $bindable(""), placeholder = "Search...", ...rest }: { value?: string; placeholder?: string; [key: string]: any } = $props();
</script>

<input
  {...rest}
  bind:value
  type="text"
  {placeholder}
  class="w-full rounded-full border-2 border-gray-300 px-3 py-2 font-serif focus:border-blue-500 focus:outline-none"
  autofocus
/>
